const images = {
	// image
	AlbumDefault: require('./image/img_albumdefault.png'),
	Arrow: require('./image/img_arrow.png'),
	ArrowBlue: require('./image/img_arrowblue.png'),
	ArrowGrey: require('./image/img_arrowgrey.png'),
	Asterisk: require('./image/img_asterisk.png'),
	
	Drop: require( './image/img_drop.png'),
	DropdownDown: require('./image/img_dropdown_down.png'),
	DropdownUp: require('./image/img_dropdown_up.png'),
	DropdownDownGrey: require('./image/img_dropdown_downgrey.png'),
	DropdownUpGrey: require('./image/img_dropdown_upgrey.png'),
	EmptyAlbum: require('./image/img_empty_album.png'),
	EmptyPerformance: require('./image/img_empty_performance.png'),

	HorizonLine: require( './image/img_horizonline.png'),
	Logo: require('./image/img_logo.png'),
	Plus: require('./image/img_plus.png'),
	ProfileDefault: require('./image/img_profiledefault.png'),
	Prop: require('./image/img_prop.png'),
	SplitMoney: require('./image/img_splitmoney.png'),

	Walkthorugh01: require('./image/img_walkthrough01.png'),
	Walkthorugh02: require('./image/img_walkthrough02.png'),
	Walkthorugh03: require('./image/img_walkthrough03.png'),
	Wallet: require('./image/img_wallet.png'),

	// button
	BtnAgreement: require('./button/btn_agreement.png'),
	BtnAgreementSelected: require('./button/btn_agreement_select.png'),
	BtnBack: require('./button/btn_back.png'),
	BtnBackBlue: require('./button/btn_backblue.png'),
	BtnBackWhite: require('./button/btn_backwhite.png'),
	BtnClose: require('./button/btn_close.png'),
	BtnCloseWhite: require('./button/btn_closewhite.png'),
	
	// icon
	TabDashboard: require('./icon/tabbar/icon_dashboard.png'),
	TabEmpty: require('./icon/tabbar/icon_empty.png'),
	TabRegisterContract: require('./icon/tabbar/icon_registerContract.png'),
	TabDocument: require('./icon/tabbar/icon_document.png'),
	TabTimeline: require('./icon/tabbar/icon_timeline.png'),
	TabTransfer: require('./icon/tabbar/icon_transfer.png'),
	IconAlbum: require('./icon/icon_album.png'),
	IconUser: require('./icon/icon_user.png'),
	IconTime: require('./icon/icon_time.png'),
	IconRemove: require('./icon/icon_remove.png'),
	IconQuestion: require('./icon/icon_question.png'),
	IconSearch: require('./icon/icon_search.png'),
	
	// key image
	KeyList: [require('./image/key/img_key01.png'),
		require('./image/key/img_key02.png'),
		require('./image/key/img_key03.png'),
		require('./image/key/img_key04.png'),
		require('./image/key/img_key05.png'),
		require('./image/key/img_key06.png'),
		require('./image/key/img_key07.png'),
		require('./image/key/img_key08.png'),
		require('./image/key/img_key09.png'),
		require('./image/key/img_key10.png'),
		require('./image/key/img_key11.png'),
		require('./image/key/img_key12.png'),
		require('./image/key/img_key13.png'),
		require('./image/key/img_key14.png'),
		require('./image/key/img_key15.png'),
		require('./image/key/img_key16.png'),
		require('./image/key/img_key17.png'),
		require('./image/key/img_key18.png'),
		require('./image/key/img_key19.png'),
		require('./image/key/img_key20.png'),],

	BankList: [require('./image/bank/img_bank001.png'),
		require('./image/bank/img_bank002.png'),
		require('./image/bank/img_bank003.png'),
		require('./image/bank/img_bank004.png'),
		require('./image/bank/img_bank005.png'),
		require('./image/bank/img_bank006.png'),
		require('./image/bank/img_bank007.png'),
		require('./image/bank/img_bank008.png'),
		require('./image/bank/img_bank009.png'),
		require('./image/bank/img_bank010.png'),
		require('./image/bank/img_bank011.png'),
		require('./image/bank/img_bank012.png'),
		require('./image/bank/img_bank013.png'),
		require('./image/bank/img_bank014.png'),
		require('./image/bank/img_bank015.png'),
		require('./image/bank/img_bank016.png'),
		require('./image/bank/img_bank017.png'),
		require('./image/bank/img_bank018.png'),],

	StampTestEnableURI: require('./image/img_teststampenable.png'),
	StampTestDisableURI: require('./image/img_teststampdisable.png'),
	// StampTestEnableURI: '/Users/mumakil/Library/Developer/CoreSimulator/Devices/C369018A-3D9C-4D7A-95E1-171B25D0CF7A/data/Containers/Data/Application/7B65E068-6589-4155-8F9F-2A0CB7942B50/tmp/ReactNative/15C1C3F3-EFE8-4BBF-BF79-43552A68AAFD.png',
	// StampTestDisableURI: '/Users/mumakil/Library/Developer/CoreSimulator/Devices/C369018A-3D9C-4D7A-95E1-171B25D0CF7A/data/Containers/Data/Application/7B65E068-6589-4155-8F9F-2A0CB7942B50/tmp/ReactNative/56D9FCA5-BE83-4D22-A86E-67EC1CBE2841.png',
};

export default images;